### ISSUE TITLE
Question 5 type error

### ISSUE THREAD

**Issue by gabrielcarino** [learn-co-curriculum/phase-1-quiz-javascript-and-the-dom#1]
### Canvas Link

https://learning.flatironschool.com/courses/4617/quizzes/25506

### Concern

the drop down menu of answers lists getElementsByID() instead of getElementsById

**Comment by lizbur10** [comment]
Hi @gabrielcarino ! Thanks for bringing this to our attention! The error has now been fixed, so I'm going to go ahead and close this issue. Please note that the change may not appear in Canvas right away.

Thanks for contributing to the Flatiron School curriculum 💙
