### ISSUE TITLE
Bad practice shown in answer

### ISSUE THREAD

**Issue by codified45** [learn-co-curriculum/phase-1-quiz-javascript-and-the-dom#2]
### Canvas Link

https://learning.flatironschool.com/courses/6190/quizzes/43188/take/questions/292619

### Concern

Question #8 (at least in my instance of the Quiz):

> Which document method takes a CSS selector as an argument and returns all elements that match? Fill in the blank:
> document.___________("**#hello**");

> answer: querySelectorAll

Aren't IDs supposed to be unique and only refer to one element? I know it's "possible" to have multiple elements with the same ID but should bad practice be shown on the quiz? 

I think a better example would be for the querySelectAll to be using a CSS class or tag selector.

**Comment by lizbur10** [comment]
Hi @codified45  ! Thanks for catching this! The question now uses a class selector rather than an id selector. Note that you may not see this change in your Canvas course, but it will be implemented for future cohorts.

Thanks for contributing to the Flatiron School curriculum 💙
