### ISSUE TITLE
Answer #1 in JavaScript and The DOM Quiz

### ISSUE THREAD

**Issue by twallingford** [learn-co-curriculum/phase-1-quiz-javascript-and-the-dom#3]
Hi,
I think the first answer should accept both "Hello!" and "'Hello!'" (one with single quotes and one without single quotes) because the text that is returned in the console is literally 'Hello!' but the quiz said that was wrong on my first attempt.

**Comment by lizbur10** [comment]
Hi @twallingford ! Thanks for bringing this to our attention. The accepted correct answers have been updated. Note that you may not see this change in your Canvas course, but it will be implemented for future cohorts.

Thanks for contributing to the Flatiron School curriculum 💙
