### ISSUE TITLE
Code Block in Question 1

### ISSUE THREAD

**Issue by e4c5Nf3d6** [learn-co-curriculum/phase-1-quiz-javascript-and-the-dom#6]
### Canvas Link

https://learning.flatironschool.com/courses/6382/quizzes/45674

### Concern

I think the code block in the first question is missing its tags.

This is what I see:
```
id="firstHeading" class="firstHeading">Hello! id="name" class="name">My name is
Ian! id="welcome" class="welcome">Welcome to my portfolio! Lorem ipsum dolor sit
amet, consectetur adipiscing elit. Pellentesque lacinia pretium feugiat.
Praesent tincidunt non odio sed ultricies. Fusce cursus nisi quis est varius
imperdiet.
```

The question asks what text will be returned from typing the following into the console:
`document.querySelector("h1").textContent;`

Since there is no h1 tag in the HTML, this was a bit confusing.

### Additional Context

Here is what I saw after I finished the quiz. The code block looked the same on the actual page for the question in the quiz.
<img width="382" alt="Screenshot 2023-04-11 223237" src="https://user-images.githubusercontent.com/126936414/231341986-f83cb7a4-b93b-44b0-8ddc-79e1bba08560.png">

### Suggested Changes

Unless the tags were intentionally left out, adding the tags in would fix the issue.

**Comment by lizbur10** [comment]
Hi @e4c5Nf3d6 ! Thanks for bringing this to our attention. It has now been fixed 💙
