### ISSUE TITLE
Lacking Information in JavaScript and The DOM Quiz Question

### ISSUE THREAD

**Issue by NomadLyfe** [learn-co-curriculum/phase-1-quiz-javascript-and-the-dom#7]
### Canvas Link

https://learning.flatironschool.com/courses/6382/quizzes/45674/take/questions/311792

### Concern

The HTML snippets are missing the tags making the questions in the quiz impossible to answer. In the additional context, I copied the information given in the quiz for the question that is not possible to get the right answer without guessing luckily (although one can assume that 'Hello!' is the right answer).

### Additional Context

The following code block is a snippet of HTML from Ian's portfolio page:

id="firstHeading" class="firstHeading">Hello! id="name" class="name">My name is
Ian! id="welcome" class="welcome">Welcome to my portfolio! Lorem ipsum dolor sit
amet, consectetur adipiscing elit. Pellentesque lacinia pretium feugiat.
Praesent tincidunt non odio sed ultricies. Fusce cursus nisi quis est varius
imperdiet.

If I am viewing this HTML in the browser, what text will be returned if I type the following into the console?

document.querySelector("h1").textContent;

### Suggested Changes

Add the tags into the HTML snippets.

**Comment by lizbur10** [comment]
Hi @NomadLyfe ! Thanks for bringing this to our attention. It has now been fixed 💙
